# Generated by Django 2.0.9 on 2018-10-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug_id', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(help_text="Instead of editing this text, you probably want to disable this ReferralSource and create a new one. If you edit this, you'll also update the referral sources for donations already made.", max_length=256, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.BigIntegerField(blank=True, help_text='Enter an integer. Reasons will be ordered from smallest to largest.', null=True)),
            ],
        ),
    ]
