# Generated by Django 2.0.9 on 2018-10-05 11:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import eaa_donations.donations.models.pledge
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_referralsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('personal_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_time', models.DateTimeField()),
                ('ip', models.GenericIPAddressField(null=True)),
                ('reference', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254)),
                ('subscribe_to_updates', models.BooleanField(default=False, verbose_name='Send me news and updates')),
                ('payment_method', enumfields.fields.EnumIntegerField(enum=eaa_donations.donations.models.pledge.PaymentMethod)),
                ('recurring', models.BooleanField()),
                ('how_did_you_hear_about_us_db', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donations.ReferralSource', verbose_name='How did you hear about us?')),
            ],
        ),
        migrations.CreateModel(
            name='PledgeComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('partner_charity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='donations.PartnerCharity')),
                ('pledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='donations.Pledge')),
            ],
        ),
        migrations.AddField(
            model_name='gift',
            name='pledge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Pledge'),
        ),
        migrations.AlterUniqueTogether(
            name='pledgecomponent',
            unique_together={('pledge', 'partner_charity')},
        ),
    ]
