# Generated by Django 2.1.2 on 2018-10-06 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_auto_20181005_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('reference', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('fees', models.FloatField()),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='donations.Donation')),
                ('pledge_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donations.PledgeComponent')),
            ],
        ),
        migrations.CreateModel(
            name='PaypalTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
            ],
        ),
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation')),
            ],
        ),
        migrations.RenameField(
            model_name='pledge',
            old_name='how_did_you_hear_about_us_db',
            new_name='referral_source',
        ),
        migrations.AddField(
            model_name='donation',
            name='pledge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='donations.Pledge'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='donations.Donation'),
        ),
    ]
