# Generated by Django 2.1.2 on 2018-10-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20181006_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pledge',
            old_name='subscribe_to_updates',
            new_name='subscribe',
        ),
    ]
